<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-R5GDS62" name="TestNG tests" tests="40" failures="23" timestamp="18 Jun 2020 08:39:07 GMT" time="5.307" errors="0">
  <testcase name="testSelect" time="0.641" classname="dao.LoaiNhaCCDAONGTest"/>
  <testcase name="test_Delete" time="0.812" classname="dao.LoaiNhaCCDAONGTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NullPointerException but got org.testng.TestException: 
Expected exception java.lang.NullPointerException but got java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint &amp;quot;FK_NhaCungCap_LoaiNhaCC&amp;quot;. The conflict occurred in database &amp;quot;DA1_QLKho&amp;quot;, table &amp;quot;dbo.NhaCungCap&amp;quot;, column &amp;apos;MaLoaiCC&amp;apos;.">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.NullPointerException but got java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
Expected exception java.lang.NullPointerException but got java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	... 15 more
Caused by: java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.LoaiNhaCCDAO.delete(LoaiNhaCCDAO.java:31)
	at dao.LoaiNhaCCDAONGTest.test_Delete(LoaiNhaCCDAONGTest.java:88)
	... 17 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_NhaCungCap_LoaiNhaCC". The conflict occurred in database "DA1_QLKho", table "dbo.NhaCungCap", column 'MaLoaiCC'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_Delete -->
  <testcase name="test_Exists" time="0.171" classname="dao.LoaiNhaCCDAONGTest"/>
  <testcase name="test_Insert" time="0.047" classname="dao.LoaiNhaCCDAONGTest">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint &amp;apos;PK_LoaiNhaCC&amp;apos;. Cannot insert duplicate key in object &amp;apos;dbo.LoaiNhaCC&amp;apos;. The duplicate key value is (MLCC02).">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_LoaiNhaCC'. Cannot insert duplicate key in object 'dbo.LoaiNhaCC'. The duplicate key value is (MLCC02).
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.LoaiNhaCCDAO.insert(LoaiNhaCCDAO.java:23)
	at dao.LoaiNhaCCDAONGTest.test_Insert(LoaiNhaCCDAONGTest.java:61)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_LoaiNhaCC'. Cannot insert duplicate key in object 'dbo.LoaiNhaCC'. The duplicate key value is (MLCC02).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- test_Insert -->
  <testcase name="test_Update" time="0.531" classname="dao.LoaiNhaCCDAONGTest"/>
  <testcase name="testDelete" time="0.047" classname="dao.NguoiDungDAONGTest"/>
  <testcase name="testFindById" time="0.032" classname="dao.NguoiDungDAONGTest"/>
  <testcase name="testInsert" time="0.031" classname="dao.NguoiDungDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.NguoiDungDAO.insert(NguoiDungDAO.java:24)
	at dao.NguoiDungDAONGTest.testInsert(NguoiDungDAONGTest.java:50)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testInsert -->
  <testcase name="testSelect" time="0.235" classname="dao.NguoiDungDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [Thien, Di, Thuan, Bang, Nhut]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [Thien, Di, Thuan, Bang, Nhut]
	at dao.NguoiDungDAONGTest.testSelect(NguoiDungDAONGTest.java:86)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSelect -->
  <testcase name="testUpdate" time="0.015" classname="dao.NguoiDungDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.NguoiDungDAO.update(NguoiDungDAO.java:29)
	at dao.NguoiDungDAONGTest.testUpdate(NguoiDungDAONGTest.java:62)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate -->
  <testcase name="testDelete" time="0.172" classname="dao.NhaCungCapDAONGTest"/>
  <testcase name="testFindById" time="0.016" classname="dao.NhaCungCapDAONGTest"/>
  <testcase name="testIsert" time="0.031" classname="dao.NhaCungCapDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.NhaCungCapDAO.isert(NhaCungCapDAO.java:23)
	at dao.NhaCungCapDAONGTest.testIsert(NhaCungCapDAONGTest.java:50)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testIsert -->
  <testcase name="testSelect" time="0.016" classname="dao.NhaCungCapDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [Cong ty A, Cong ty B, Cong ty C, Cong ty D, Cong ty E]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [Cong ty A, Cong ty B, Cong ty C, Cong ty D, Cong ty E]
	at dao.NhaCungCapDAONGTest.testSelect(NhaCungCapDAONGTest.java:87)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSelect -->
  <testcase name="testUpdate" time="0.0" classname="dao.NhaCungCapDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.NhaCungCapDAO.update(NhaCungCapDAO.java:28)
	at dao.NhaCungCapDAONGTest.testUpdate(NhaCungCapDAONGTest.java:62)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate -->
  <testcase name="testDelete" time="0.249" classname="dao.PhieuNhapDAONGTest">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint &amp;quot;FK_SanPham_SanPham&amp;quot;. The conflict occurred in database &amp;quot;DA1_QLKho&amp;quot;, table &amp;quot;dbo.SanPham&amp;quot;, column &amp;apos;MaNhap&amp;apos;.">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_SanPham_SanPham". The conflict occurred in database "DA1_QLKho", table "dbo.SanPham", column 'MaNhap'.
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.PhieuNhapDAO.delete(PhieuNhapDAO.java:37)
	at dao.PhieuNhapDAONGTest.testDelete(PhieuNhapDAONGTest.java:87)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The DELETE statement conflicted with the REFERENCE constraint "FK_SanPham_SanPham". The conflict occurred in database "DA1_QLKho", table "dbo.SanPham", column 'MaNhap'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testDelete -->
  <testcase name="testFindById" time="0.079" classname="dao.PhieuNhapDAONGTest"/>
  <testcase name="testInsert" time="0.115" classname="dao.PhieuNhapDAONGTest">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint &amp;apos;PK_PhieuNhap&amp;apos;. Cannot insert duplicate key in object &amp;apos;dbo.PhieuNhap&amp;apos;. The duplicate key value is (N07).">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_PhieuNhap'. Cannot insert duplicate key in object 'dbo.PhieuNhap'. The duplicate key value is (N07).
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.PhieuNhapDAO.insert(PhieuNhapDAO.java:26)
	at dao.PhieuNhapDAONGTest.testInsert(PhieuNhapDAONGTest.java:60)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_PhieuNhap'. Cannot insert duplicate key in object 'dbo.PhieuNhap'. The duplicate key value is (N07).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testInsert -->
  <testcase name="testSelect" time="0.04" classname="dao.PhieuNhapDAONGTest"/>
  <testcase name="testUpdate" time="0.312" classname="dao.PhieuNhapDAONGTest"/>
  <testcase name="testDelete" time="0.092" classname="dao.PhieuXuatDAONGTest"/>
  <testcase name="testFindById" time="0.196" classname="dao.PhieuXuatDAONGTest"/>
  <testcase name="testInsert" time="0.0" classname="dao.PhieuXuatDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.PhieuXuatDAO.insert(PhieuXuatDAO.java:22)
	at dao.PhieuXuatDAONGTest.testInsert(PhieuXuatDAONGTest.java:50)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testInsert -->
  <testcase name="testSelect" time="0.047" classname="dao.PhieuXuatDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [SP1(2019-05-10), SP2(2018-07-11), SP2(2019-10-13), SP3(2019-01-01), SP5(2018-02-02)]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [SP1(2019-05-10), SP2(2018-07-11), SP2(2019-10-13), SP3(2019-01-01), SP5(2018-02-02)]
	at dao.PhieuXuatDAONGTest.testSelect(PhieuXuatDAONGTest.java:87)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSelect -->
  <testcase name="testSelectByKeyword" time="0.359" classname="dao.PhieuXuatDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [SP1(2019-05-10), SP2(2018-07-11), SP2(2019-10-13), SP3(2019-01-01), SP5(2018-02-02)]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [SP1(2019-05-10), SP2(2018-07-11), SP2(2019-10-13), SP3(2019-01-01), SP5(2018-02-02)]
	at dao.PhieuXuatDAONGTest.testSelectByKeyword(PhieuXuatDAONGTest.java:101)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSelectByKeyword -->
  <testcase name="testUpdate" time="0.015" classname="dao.PhieuXuatDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.PhieuXuatDAO.update(PhieuXuatDAO.java:29)
	at dao.PhieuXuatDAONGTest.testUpdate(PhieuXuatDAONGTest.java:62)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate -->
  <testcase name="testDelete" time="0.079" classname="dao.SanPhamDAONGTest"/>
  <testcase name="testFindById" time="0.015" classname="dao.SanPhamDAONGTest"/>
  <testcase name="testInsert" time="0.016" classname="dao.SanPhamDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.SanPhamDAO.insert(SanPhamDAO.java:23)
	at dao.SanPhamDAONGTest.testInsert(SanPhamDAONGTest.java:50)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testInsert -->
  <testcase name="testSelectByKeyword" time="0.297" classname="dao.SanPhamDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [Sua, Bia, Bin sạc dự phòng, Ổ điện, Pepsi, Điện Thoại, Nồi cơm điện, Laptop, Đậu hủ, Quật gió, Bóng đèn, Loa]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [Sua, Bia, Bin sạc dự phòng, Ổ điện, Pepsi, Điện Thoại, Nồi cơm điện, Laptop, Đậu hủ, Quật gió, Bóng đèn, Loa]
	at dao.SanPhamDAONGTest.testSelectByKeyword(SanPhamDAONGTest.java:101)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSelectByKeyword -->
  <testcase name="testSelect_0args" time="0.047" classname="dao.SanPhamDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [Sua, Bia, Bin sạc dự phòng, Ổ điện, Pepsi, Điện Thoại, Nồi cơm điện, Laptop, Đậu hủ, Quật gió, Bóng đèn, Loa]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [Sua, Bia, Bin sạc dự phòng, Ổ điện, Pepsi, Điện Thoại, Nồi cơm điện, Laptop, Đậu hủ, Quật gió, Bóng đèn, Loa]
	at dao.SanPhamDAONGTest.testSelect_0args(SanPhamDAONGTest.java:87)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSelect_0args -->
  <testcase name="testSelect_String_ObjectArr" time="0.015" classname="dao.SanPhamDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.SanPhamDAO.select(SanPhamDAO.java:65)
	at dao.SanPhamDAONGTest.testSelect_String_ObjectArr(SanPhamDAONGTest.java:129)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testSelect_String_ObjectArr -->
  <testcase name="testUpdate" time="0.0" classname="dao.SanPhamDAONGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at dao.SanPhamDAO.update(SanPhamDAO.java:30)
	at dao.SanPhamDAONGTest.testUpdate(SanPhamDAONGTest.java:62)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate -->
  <testcase name="testGetNhapKho" time="0.032" classname="dao.ThongKeDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: []">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: []
	at dao.ThongKeDAONGTest.testGetNhapKho(ThongKeDAONGTest.java:51)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testGetNhapKho -->
  <testcase name="testGetXuatKho" time="0.031" classname="dao.ThongKeDAONGTest">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: []">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: []
	at dao.ThongKeDAONGTest.testGetXuatKho(ThongKeDAONGTest.java:65)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testGetXuatKho -->
  <testcase name="testDelete" time="0.078" classname="dao.ThongTinKhoDAONGTest"/>
  <testcase name="testFindById" time="0.016" classname="dao.ThongTinKhoDAONGTest"/>
  <testcase name="testInsert" time="0.015" classname="dao.ThongTinKhoDAONGTest">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint &amp;apos;PK_ThongTinKho&amp;apos;. Cannot insert duplicate key in object &amp;apos;dbo.ThongTinKho&amp;apos;. The duplicate key value is (K09).">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ThongTinKho'. Cannot insert duplicate key in object 'dbo.ThongTinKho'. The duplicate key value is (K09).
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.ThongTinKhoDAO.insert(ThongTinKhoDAO.java:24)
	at dao.ThongTinKhoDAONGTest.testInsert(ThongTinKhoDAONGTest.java:55)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ThongTinKho'. Cannot insert duplicate key in object 'dbo.ThongTinKho'. The duplicate key value is (K09).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testInsert -->
  <testcase name="testSelect" time="0.047" classname="dao.ThongTinKhoDAONGTest"/>
  <testcase name="testUpdate" time="0.016" classname="dao.ThongTinKhoDAONGTest">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint &amp;apos;PK_ThongTinKho&amp;apos;. Cannot insert duplicate key in object &amp;apos;dbo.ThongTinKho&amp;apos;. The duplicate key value is (K08).">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ThongTinKho'. Cannot insert duplicate key in object 'dbo.ThongTinKho'. The duplicate key value is (K08).
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:53)
	at dao.ThongTinKhoDAO.insert(ThongTinKhoDAO.java:24)
	at dao.ThongTinKhoDAONGTest.testUpdate(ThongTinKhoDAONGTest.java:69)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_ThongTinKho'. Cannot insert duplicate key in object 'dbo.ThongTinKho'. The duplicate key value is (K08).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1655)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:385)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7505)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2445)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:191)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:166)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:328)
	at Helper.JdbcHelper.executeUpdate(JdbcHelper.java:47)
	... 25 more
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate -->
</testsuite> <!-- TestNG tests -->
